export const qk = {
  me: () => ['me'] as const,
  jobs: (f?: Record<string, unknown>) => ['jobs', f ?? {}] as const,
  job: (id: number) => ['jobs', id] as const,
  jobQuestions: (id: number) => ['jobs', id, 'questions'] as const,
  tailoredResumeStatus: (id: number) => ['jobs', id, 'tailored-resume-status'] as const,
  coverLetterStatus: (id: number) => ['jobs', id, 'cover-letter-status'] as const,
  analyzeResumeStatus: (jobId: string) => ['resume', 'analyze', jobId, 'status'] as const,
  linkedinTailoredResumeStatus: (id: number) => ['linkedin-post', id, 'tailored-resume-status'] as const,
  linkedinEmailStatus: (id: number) => ['linkedin-post', id, 'email-status'] as const,
  queue: () => ['queue'] as const,
  resume: () => ['resume'] as const,
  settings: () => ['settings'] as const,
  stats: () => ['stats'] as const,
  openrouterCredits: () => ['openrouter', 'credits'] as const,
  linkedinPosts: (page?: number, filters?: Record<string, unknown>) => page === undefined && filters === undefined ? (['linkedin-posts'] as const) : (['linkedin-posts', page ?? 1, filters ?? {}] as const),
  linkedinPost: (id: number) => ['linkedin-post', id] as const,
  linkedinBatch: (batchId: string) => ['linkedin-batch', batchId] as const,
  linkedinBatches: () => ['linkedin-batches'] as const,
  linkedinPostQuestions: (id: number) => ['linkedin-post', id, 'questions'] as const,
  linkedinReminders: () => ['linkedin-reminders'] as const,
  recruiterContact: (email: string) => ['recruiter-contact', email] as const,
};
