export const qk = {
  me: () => ['me'] as const,
  jobs: (f?: Record<string, unknown>) => ['jobs', f ?? {}] as const,
  job: (id: number) => ['jobs', id] as const,
  jobQuestions: (id: number) => ['jobs', id, 'questions'] as const,
  queue: () => ['queue'] as const,
  resume: () => ['resume'] as const,
  settings: () => ['settings'] as const,
  stats: () => ['stats'] as const,
  openrouterCredits: () => ['openrouter', 'credits'] as const,
  linkedinPosts: (page?: number, filters?: Record<string, unknown>) => ['linkedin-posts', page ?? 1, filters ?? {}] as const,
  linkedinPost: (id: number) => ['linkedin-post', id] as const,
  linkedinBatch: (batchId: string) => ['linkedin-batch', batchId] as const,
  linkedinPostQuestions: (id: number) => ['linkedin-post', id, 'questions'] as const,
};
